#
# Common bash configuration.
# 
# If additional machine-specific configs are required, such as env variables,
# they can be set inside a local bash dotfile, from which this file can then
# be sourced.
#
# If this script is sourced with the arg '--moz_profile' supplied, the
# ./moz_profile script will be run (note that this may not work if this script
# is sourced via a symlink).
#
# If this script is sourced with the arg '--mozaws' supplied, the
# ./mozaws_profile script will be run (note that this may not work if this script
# is sourced via a symlink).
#

while [[ $# -gt 0 ]]; do
    case "$1" in
        --moz_profile) USE_MOZ_PROFILE="true" ;;
        --mozaws) USE_MOZAWS="true" ;;
    esac
    shift
done

# Enhanced bash completion, as installed using Homebrew.
# Try looking for newer version first.
BASH_COMP="/usr/local/etc/bash_completion"
BASH_COMP_2="/usr/local/share/bash-completion/bash_completion"
if [[ -r "$BASH_COMP_2" ]]; then
    . "$BASH_COMP_2"
elif [[ -r "$BASH_COMP" ]]; then
    . "$BASH_COMP"
fi

# Customization for less.
export LESS="--quit-if-one-screen --long-prompt --no-init --RAW-CONTROL-CHARS"

# Customized command prompt.
#
# If the variable HOST_NICKNAME is set, use it in the prompt.
# Otherwise, use the short form of the hostname.
#
# Add info for git repos, if functionality is available:
# - branch
# - dirtiness indicator
# - untracked files indicator
GIT_PS1_CMD="$(command -v __git_ps1)"
if [[ -n "$GIT_PS1_CMD" ]]; then
    export GIT_PS1_SHOWUNTRACKEDFILES=true
    export GIT_PS1_SHOWDIRTYSTATE=true
    #export GIT_PS1_SHOWUPSTREAM="auto"
    GIT_PS1_CMD=$(printf '$(%s)' $GIT_PS1_CMD)
fi
export PS1="$(printf '%s@%s: \W%s }\$ ' \
                "\u" \
                "${HOST_NICKNAME:-\h}" \
                "$GIT_PS1_CMD")"

# Completion for AWS. Should be in PATH.
AWS_COMP="$(command -v aws_completer)"
[[ -n "$AWS_COMP" ]] && complete -C "$AWS_COMP" aws


# Customized views for (GNU) ls. 
# Always use colours.
alias ls='ls --color=auto'
# Customized short form. 
alias la='ls -A --group-directories-first'
# Customized long form.
alias ll='ls -lAh'
# Always use Vim (for cases where applications default to opening vi).
alias vi='vim'
# Rmarkdown rendering.
alias rmd='render_rmd'

# R
#alias R='R --no-save'

# Render an Rmarkdown file to HTML.
render_rmd() {
    Rscript --vanilla -e "rmarkdown::render('$1')"
}

# Shortcut that works like ls for dirs and less for files.
#list_or_less() {
#    TARGET="$1"
#    [[ -z "$TARGET" ]] && TARGET="."
#    [[ -f 
#}
#

# Source additional config scripts if required.
THIS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
[[ "$USE_MOZ_PROFILE" == "true" ]] && . "$THIS_DIR/moz_profile"
[[ "$USE_MOZAWS" == "true" ]] && . "$THIS_DIR/mozaws_profile"

