#
# Common bash configuration.
# 
# If additional machine-specific configs are required, such as env variables,
# they can be set inside a local bash dotfile, from which this file can then
# be sourced.
#


# Enhanced bash completion.
BASH_COMP="/usr/local/etc/bash_completion"
[ -r $BASH_COMP ] && . $BASH_COMP

# Customization for less.
export LESS="--quit-if-one-screen --long-prompt --no-init --RAW-CONTROL-CHARS"

# Customized command prompt.
#
# If the variable HOST_NICKNAME is set, use it in the prompt.
# Otherwise, use the hostname.
#
# Add info for git repos, if functionality is available:
# - branch
# - dirtiness indicator
# - untracked files indicator
GIT_PS1_CMD=$(command -v __git_ps1)
if [ -n $GIT_PS1_CMD ]; then
    export GIT_PS1_SHOWUNTRACKEDFILES=true
    export GIT_PS1_SHOWDIRTYSTATE=true
    #export GIT_PS1_SHOWUPSTREAM="auto"
    GIT_PS1_CMD=$(printf '$(%s)' $GIT_PS1_CMD)
fi
export PS1=$(printf '%s@:%s \W%s }\$ ' \
                "\u" \
                "${HOST_NICKNAME:-$HOSTNAME}" \
                "$GIT_PS1_CMD")

# Customized views for (GNU) ls. 
# Always use colours.
alias ls='ls --color=auto'
# Customized short form. 
alias la='ls -A --group-directories-first'
# Customized long form.
alias ll='ls -lAUh'

# R
#alias R='R --no-save'

